### ISSUE TITLE
CI/CD 구축

### ISSUE THREAD

**Issue by ybkim-dev** [prgrms-web-devcourse/Team-JJINSA-HyperLink-BE#5]
- Github Actions를 활용한 CI
- AWS Code Deploy를 활용한 CD 
- ELB를 활용한 Blue/Green 무중단 배포

**Comment by ybkim-dev** [comment]
- 민감 정보를 S3에 업로드해도 되는지 확실하지 않아 일단 보류하겠습니다.
- 그 외의 작업들은 마무리되었고 민감정보 업로드 여부만 결정나면 Blue/Green을 활용한 무중단 배포 가능합니다.
- 현재는 CI만 적용되어 있습니다.

**Comment by yeeeze** [comment]
이슈에 해당되는 PR 생성하면서 이슈 연결해주세요!
CI/CD 관련된 PR은 팀원들이 확인가능하도록 기웅님, 저 모두 리뷰어 등록 부탁드려요 😊
